services:
  - type: web
    name: premium-video-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: ""
        sync: false
